Starting with the data transformation pipeline
Rigved-Harmalkar/Hate-Speech-Classification pull request #3
Opened 2024-12-19 19:23 UTC by Rigved-Harmalkar

Some lines of code not much. Will complete the data transformation pipeline tomorrow.

2024-12-20 08:47 UTC, ashish-k-r requested changes
Add .zip, .log to .gitignore so that they don't show up when you are trying to push your changes as they're not required I presume? 

Also update the description of the PR with exactly what you are trying to achieve.

If there are suitable unit tests applicable to test the implementation add them.

2024-12-20 10:16 UTC, Rigved-Harmalkar commented
> Add .zip, .log to .gitignore so that they don't show up when you are trying to push your changes as they're not required I presume?
> 
> Also update the description of the PR with exactly what you are trying to achieve.
> 
> If there are suitable unit tests applicable to test the implementation add them.

Since I am ingesting data from Google Cloud platform bucket the data stored in there is in .zip format and .log are the logs that are artifacts after running the program but it's a good idea to not include the .log into the git as it is for my reference thank you for the feedback shall make the changes asap! For now there are no test cases but in future there might be.

2024-12-20 14:17 UTC, ashish-k-r commented
> > Add .zip, .log to .gitignore so that they don't show up when you are trying to push your changes as they're not required I presume?
> > Also update the description of the PR with exactly what you are trying to achieve.
> > If there are suitable unit tests applicable to test the implementation add them.
> 
> Since I am ingesting data from Google Cloud platform bucket the data stored in there is in .zip format and .log are the logs that are artifacts after running the program but it's a good idea to not include the .log into the git as it is for my reference thank you for the feedback shall make the changes asap! For now there are no test cases but in future there might be.

the .zip file will not be used though I suppose, a better method to load data would be:-
1. Get a signed URL for the .zip file from Google Cloud Storage.
2. Stream the .zip file from the URL and extract it directly into memory without saving it to a file.

if you can, or else we can discuss the limitations to this approach.

also try to rename the environment you're using in the readme.md.

2024-12-21 18:12 UTC, ashish-k-r approved these changes

2024-12-21 18:20 UTC, merged